import path from 'node:path'
import { fileURLToPath } from 'node:url'

import tailwindcss from '@tailwindcss/vite'
import { tanstackRouter } from '@tanstack/router-plugin/vite'
import react from '@vitejs/plugin-react'
import { defineConfig, loadEnv } from 'vite'

const dirname = path.dirname(fileURLToPath(import.meta.url))

// https://vite.dev/config/
export default defineConfig(({ command, mode }) => {
  const env = loadEnv(mode, dirname, '')
  const apiProxyTarget = env.API_PROXY_TARGET ?? 'http://127.0.0.1:8000'
  // Read here, by the dev proxy, and nowhere else: without the VITE_ prefix
  // Vite never exposes it to client code, so the browser never holds it (#149).
  const apiKey = env.API_KEY ?? ''
  if (command === 'serve' && !apiKey) {
    console.warn('API_KEY is not set: the /api proxy sends no X-API-Key and the API will answer 401.')
  }

  return {
    plugins: [
      tanstackRouter({
        routesDirectory: './src/app/router/routes',
        generatedRouteTree: './src/app/router/routeTree.gen.ts',
        target: 'react',
      }),
      react(),
      tailwindcss(),
    ],
    resolve: {
      alias: {
        '@': path.resolve(dirname, './src'),
      },
    },
    build: {
      // Lowered, not raised. The single 514 kB bundle sat just above Vite's
      // 500 kB default, so the warning had become background noise. The entry
      // chunk is ~370 kB once the routes are split; 400 leaves room to breathe
      // and trips again well before the old size comes back.
      chunkSizeWarningLimit: 400,
    },
    test: {
      // jsdom rather than the default node environment: every hook under test
      // renders, and Testing Library needs a DOM to render into.
      environment: 'jsdom',
      globals: true,
      setupFiles: ['./src/test/setup.ts'],
      // Route files are generated by the router plugin and assert nothing.
      exclude: ['node_modules/**', 'dist/**', 'src/app/router/routeTree.gen.ts'],
      coverage: {
        provider: 'v8',
        reporter: ['text-summary'],
        include: ['src/features/**/*.{ts,tsx}'],
      },
    },
    server: {
      proxy: {
        '/api': {
          target: apiProxyTarget,
          changeOrigin: true,
          // Lower-case, like Node's incoming header names, so it overwrites an
          // `x-api-key` a client sends instead of travelling next to it.
          ...(apiKey ? { headers: { 'x-api-key': apiKey } } : {}),
        },
      },
    },
  }
})
