import path from 'node:path'
import { fileURLToPath } from 'node:url'

import tailwindcss from '@tailwindcss/vite'
import { tanstackRouter } from '@tanstack/router-plugin/vite'
import react from '@vitejs/plugin-react'
import { defineConfig, loadEnv } from 'vite'

const dirname = path.dirname(fileURLToPath(import.meta.url))

// https://vite.dev/config/
export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, dirname, '')
  const apiProxyTarget = env.API_PROXY_TARGET ?? 'http://127.0.0.1:8000'

  return {
    plugins: [
      tanstackRouter({
        routesDirectory: './src/app/router/routes',
        generatedRouteTree: './src/app/router/routeTree.gen.ts',
        target: 'react',
      }),
      react(),
      tailwindcss(),
    ],
    resolve: {
      alias: {
        '@': path.resolve(dirname, './src'),
      },
    },
    test: {
      // jsdom rather than the default node environment: every hook under test
      // renders, and Testing Library needs a DOM to render into.
      environment: 'jsdom',
      globals: true,
      setupFiles: ['./src/test/setup.ts'],
      // Route files are generated by the router plugin and assert nothing.
      exclude: ['node_modules/**', 'dist/**', 'src/app/router/routeTree.gen.ts'],
      coverage: {
        provider: 'v8',
        reporter: ['text-summary'],
        include: ['src/features/**/*.{ts,tsx}'],
      },
    },
    server: {
      proxy: {
        '/api': {
          target: apiProxyTarget,
          changeOrigin: true,
        },
      },
    },
  }
})
