"""Initial schema — the 16 tables of docs/architecture/DATA_MODEL.md.

Generated by autogenerate against an empty Postgres 16, so it is a faithful
diff of infrastructure/persistence/tables.py rather than a hand transcription.
tests/integration/test_migrations.py asserts the two stay in agreement.

Revision ID: 0001
Revises:
Create Date: 2026-09-08 16:11:44.036625
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "agent",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent")),
        sa.UniqueConstraint("name", "version", name="uq_agent_name_version"),
        comment="One observed coding agent: claude-code, codex.",
    )
    op.create_table(
        "data_source",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("license", sa.Text(), nullable=True),
        sa.Column("dataset_version", sa.Text(), nullable=True),
        sa.Column("retrieved_at", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_source")),
        sa.UniqueConstraint("slug", name=op.f("uq_data_source_slug")),
        comment="One identified external dataset, with its version and retrieval date.",
    )
    op.create_table(
        "file_upload",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("original_name", sa.Text(), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("format", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("content_hash", sa.CHAR(length=64), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "format IN ('jsonl','csv','parquet')", name=op.f("ck_file_upload_format")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_upload")),
        sa.UniqueConstraint("content_hash", name=op.f("uq_file_upload_content_hash")),
        comment="One physically uploaded file, identified by its SHA-256.",
    )
    op.create_table(
        "provider",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider")),
        sa.UniqueConstraint("name", name=op.f("uq_provider_name")),
        comment="One model provider: anthropic, openai, unknown.",
    )
    op.create_table(
        "repository",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("host", sa.Text(), server_default="github.com", nullable=False),
        sa.Column("owner", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repository")),
        sa.UniqueConstraint("host", "owner", "name", name="uq_repository_host_owner_name"),
        comment="One code repository providing context for a session.",
    )
    op.create_table(
        "tool",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool")),
        sa.UniqueConstraint("name", name=op.f("uq_tool_name")),
        comment="One invocable tool, by canonical name: Read, Bash, Edit.",
    )
    op.create_table(
        "mapping",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("data_source_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("source_format", sa.Text(), nullable=False),
        sa.Column("document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), server_default="draft", nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "source_format IN ('jsonl','csv','parquet')", name=op.f("ck_mapping_source_format")
        ),
        sa.CheckConstraint(
            "status IN ('draft','validated','active','superseded','rejected','archived')",
            name=op.f("ck_mapping_status"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_mapping_version_positive")),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_source.id"],
            name=op.f("fk_mapping_data_source_id_data_source"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mapping")),
        sa.UniqueConstraint("data_source_id", "name", "version", name="uq_mapping_name_version"),
        comment="One version of a reusable import configuration.",
    )
    op.create_table(
        "model",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("provider_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("family", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["provider_id"], ["provider.id"], name=op.f("fk_model_provider_id_provider")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model")),
        sa.UniqueConstraint("provider_id", "name", name="uq_model_provider_name"),
        comment="One model identified at one provider.",
    )
    op.create_table(
        "import_run",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("data_source_id", sa.BigInteger(), nullable=False),
        sa.Column("file_upload_id", sa.BigInteger(), nullable=False),
        sa.Column("mapping_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("records_read", sa.Integer(), server_default="0", nullable=False),
        sa.Column("records_imported", sa.Integer(), server_default="0", nullable=False),
        sa.Column("records_duplicate", sa.Integer(), server_default="0", nullable=False),
        sa.Column("records_rejected", sa.Integer(), server_default="0", nullable=False),
        sa.Column("fields_missing", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.Text(), nullable=True),
        sa.Column("attempts", sa.SmallInteger(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "status IN ('pending','running','succeeded','partial','failed','cancelled')",
            name=op.f("ck_import_run_status"),
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_source.id"],
            name=op.f("fk_import_run_data_source_id_data_source"),
        ),
        sa.ForeignKeyConstraint(
            ["file_upload_id"],
            ["file_upload.id"],
            name=op.f("fk_import_run_file_upload_id_file_upload"),
        ),
        sa.ForeignKeyConstraint(
            ["mapping_id"], ["mapping.id"], name=op.f("fk_import_run_mapping_id_mapping")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_run")),
        comment="One import execution: one file x one mapping x one instant.",
    )
    op.create_index(
        "ix_import_run_pending",
        "import_run",
        ["status", "created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "mapping_proposal",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("data_source_id", sa.BigInteger(), nullable=True),
        sa.Column("file_upload_id", sa.BigInteger(), nullable=False),
        sa.Column("mapping_id", sa.BigInteger(), nullable=True),
        sa.Column("document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("validation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rationale", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ambiguities", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("unmapped_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("analyzer_provider", sa.Text(), nullable=False),
        sa.Column("analyzer_model", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_source.id"],
            name=op.f("fk_mapping_proposal_data_source_id_data_source"),
        ),
        sa.ForeignKeyConstraint(
            ["file_upload_id"],
            ["file_upload.id"],
            name=op.f("fk_mapping_proposal_file_upload_id_file_upload"),
        ),
        sa.ForeignKeyConstraint(
            ["mapping_id"], ["mapping.id"], name=op.f("fk_mapping_proposal_mapping_id_mapping")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mapping_proposal")),
        comment="One mapping proposed by an AI model for one file.",
    )
    op.create_index(
        "ix_mapping_proposal_file_upload_id", "mapping_proposal", ["file_upload_id"], unique=False
    )
    op.create_table(
        "mapping_proposal_message",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("mapping_proposal_id", sa.BigInteger(), nullable=False),
        sa.Column("turn_index", sa.Integer(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('user','assistant')", name=op.f("ck_mapping_proposal_message_role")
        ),
        sa.ForeignKeyConstraint(
            ["mapping_proposal_id"],
            ["mapping_proposal.id"],
            name=op.f("fk_mapping_proposal_message_mapping_proposal_id_mapping_proposal"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mapping_proposal_message")),
        sa.UniqueConstraint(
            "mapping_proposal_id", "turn_index", name="uq_proposal_message_proposal_turn"
        ),
        comment="One conversation turn between the user and the import agent.",
    )
    op.create_table(
        "raw_record",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("import_run_id", sa.BigInteger(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.CHAR(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["import_run_id"],
            ["import_run.id"],
            name=op.f("fk_raw_record_import_run_id_import_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_record")),
        sa.UniqueConstraint("import_run_id", "line_number", name="uq_raw_record_run_line"),
        comment="One source record exactly as it was read, before any transformation.",
    )
    op.create_index("ix_raw_record_content_hash", "raw_record", ["content_hash"], unique=False)
    op.create_table(
        "import_issue",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("import_run_id", sa.BigInteger(), nullable=False),
        sa.Column("raw_record_id", sa.BigInteger(), nullable=True),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("field_path", sa.Text(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "severity IN ('rejected','duplicate','warning')", name=op.f("ck_import_issue_severity")
        ),
        sa.ForeignKeyConstraint(
            ["import_run_id"],
            ["import_run.id"],
            name=op.f("fk_import_issue_import_run_id_import_run"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["raw_record.id"],
            name=op.f("fk_import_issue_raw_record_id_raw_record"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_issue")),
        comment="One problem on one raw_record: rejection, duplicate or warning.",
    )
    op.create_index(
        "ix_import_issue_run_severity", "import_issue", ["import_run_id", "severity"], unique=False
    )
    op.create_table(
        "session",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("data_source_id", sa.BigInteger(), nullable=False),
        sa.Column("import_run_id", sa.BigInteger(), nullable=False),
        sa.Column("raw_record_id", sa.BigInteger(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("agent_id", sa.BigInteger(), nullable=True),
        sa.Column("repository_id", sa.BigInteger(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.BigInteger(), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "outcome IN ('completed','error','aborted','unknown')", name=op.f("ck_session_outcome")
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agent.id"], name=op.f("fk_session_agent_id_agent")),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            ["data_source.id"],
            name=op.f("fk_session_data_source_id_data_source"),
        ),
        sa.ForeignKeyConstraint(
            ["import_run_id"], ["import_run.id"], name=op.f("fk_session_import_run_id_import_run")
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"], ["raw_record.id"], name=op.f("fk_session_raw_record_id_raw_record")
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"], ["repository.id"], name=op.f("fk_session_repository_id_repository")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session")),
        sa.UniqueConstraint("data_source_id", "external_id", name="uq_session_source_external"),
        comment="One agent working session, from start to finish.",
    )
    op.create_index(
        "ix_session_data_source_agent", "session", ["data_source_id", "agent_id"], unique=False
    )
    op.create_index("ix_session_started_at", "session", ["started_at"], unique=False)
    op.create_table(
        "model_call",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("session_id", sa.BigInteger(), nullable=False),
        sa.Column("raw_record_id", sa.BigInteger(), nullable=False),
        sa.Column("model_id", sa.BigInteger(), nullable=True),
        sa.Column("sequence_index", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.BigInteger(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=True),
        sa.Column("cache_creation_tokens", sa.Integer(), nullable=True),
        sa.Column("reasoning_tokens", sa.Integer(), nullable=True),
        sa.Column("stop_reason", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="unknown", nullable=False),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.CheckConstraint("status IN ('ok','error','unknown')", name=op.f("ck_model_call_status")),
        sa.ForeignKeyConstraint(
            ["model_id"], ["model.id"], name=op.f("fk_model_call_model_id_model")
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["raw_record.id"],
            name=op.f("fk_model_call_raw_record_id_raw_record"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
            name=op.f("fk_model_call_session_id_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_call")),
        sa.UniqueConstraint("session_id", "sequence_index", name="uq_model_call_session_sequence"),
        comment="One model inference call within a session.",
    )
    op.create_index("ix_model_call_model_id", "model_call", ["model_id"], unique=False)
    op.create_index("ix_model_call_session_id", "model_call", ["session_id"], unique=False)
    op.create_table(
        "tool_call",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("session_id", sa.BigInteger(), nullable=False),
        sa.Column("model_call_id", sa.BigInteger(), nullable=True),
        sa.Column("raw_record_id", sa.BigInteger(), nullable=False),
        sa.Column("tool_id", sa.BigInteger(), nullable=False),
        sa.Column("sequence_index", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.Text(), server_default="unknown", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result_size", sa.Integer(), nullable=True),
        sa.CheckConstraint("status IN ('ok','error','unknown')", name=op.f("ck_tool_call_status")),
        sa.ForeignKeyConstraint(
            ["model_call_id"],
            ["model_call.id"],
            name=op.f("fk_tool_call_model_call_id_model_call"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"], ["raw_record.id"], name=op.f("fk_tool_call_raw_record_id_raw_record")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
            name=op.f("fk_tool_call_session_id_session"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tool_id"], ["tool.id"], name=op.f("fk_tool_call_tool_id_tool")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_call")),
        sa.UniqueConstraint("session_id", "sequence_index", name="uq_tool_call_session_sequence"),
        comment="One tool invocation within a session.",
    )
    op.create_index("ix_tool_call_model_call_id", "tool_call", ["model_call_id"], unique=False)
    op.create_index("ix_tool_call_session_id", "tool_call", ["session_id"], unique=False)
    op.create_index("ix_tool_call_tool_id", "tool_call", ["tool_id"], unique=False)


def downgrade() -> None:
    op.drop_index("ix_tool_call_tool_id", table_name="tool_call")
    op.drop_index("ix_tool_call_session_id", table_name="tool_call")
    op.drop_index("ix_tool_call_model_call_id", table_name="tool_call")
    op.drop_table("tool_call")
    op.drop_index("ix_model_call_session_id", table_name="model_call")
    op.drop_index("ix_model_call_model_id", table_name="model_call")
    op.drop_table("model_call")
    op.drop_index("ix_session_started_at", table_name="session")
    op.drop_index("ix_session_data_source_agent", table_name="session")
    op.drop_table("session")
    op.drop_index("ix_import_issue_run_severity", table_name="import_issue")
    op.drop_table("import_issue")
    op.drop_index("ix_raw_record_content_hash", table_name="raw_record")
    op.drop_table("raw_record")
    op.drop_table("mapping_proposal_message")
    op.drop_index("ix_mapping_proposal_file_upload_id", table_name="mapping_proposal")
    op.drop_table("mapping_proposal")
    op.drop_index(
        "ix_import_run_pending",
        table_name="import_run",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("import_run")
    op.drop_table("model")
    op.drop_table("mapping")
    op.drop_table("tool")
    op.drop_table("repository")
    op.drop_table("provider")
    op.drop_table("file_upload")
    op.drop_table("data_source")
    op.drop_table("agent")
