"""User auth — `users` and `user_session`.

Generated by autogenerate against a Postgres 16 migrated to 0002, so it is a
faithful diff of infrastructure/persistence/tables.py rather than a hand
transcription. tests/integration/test_migrations.py asserts the two stay in
agreement.

Orthogonal to the rest of the schema: no existing table references either of
these two, and neither references anything but each other. This is per-person
login, layered on top of the app-wide `X-API-Key` gate rather than replacing
it (docs/architecture/API.md §10).

Table named `users` (plural), unlike every other table in this schema — the
singular `user` is a reserved word in the SQL standard (a synonym for
CURRENT_USER), so a bare, unquoted `user` breaks the moment anything issues
raw SQL against it (as tests/integration/conftest.py's TRUNCATE did during
development).

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-10 20:33:17.028027
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        comment="One person able to authenticate against the API.",
    )
    op.create_table(
        "user_session",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_session_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_session")),
        sa.UniqueConstraint("token", name=op.f("uq_user_session_token")),
        comment="One active login, identified by its opaque bearer token.",
    )
    op.create_index("ix_user_session_user_id", "user_session", ["user_id"], unique=False)


def downgrade() -> None:
    op.drop_index("ix_user_session_user_id", table_name="user_session")
    op.drop_table("user_session")
    op.drop_table("users")
