/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppImportAssistantIndexRouteImport } from './routes/_app.import-assistant.index'
import { Route as AppImportsIndexRouteImport } from './routes/_app.imports.index'
import { Route as AppImportsImportIdRouteImport } from './routes/_app.imports.$importId'
import { Route as AppMappingsIndexRouteImport } from './routes/_app.mappings.index'
import { Route as AppQualityIndexRouteImport } from './routes/_app.quality.index'
import { Route as AppSessionsIndexRouteImport } from './routes/_app.sessions.index'
import { Route as AppSessionsSessionIdRouteImport } from './routes/_app.sessions.$sessionId'
import { Route as AppSourcesIndexRouteImport } from './routes/_app.sources.index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppImportAssistantIndexRoute = AppImportAssistantIndexRouteImport.update({
  id: '/import-assistant/',
  path: '/import-assistant/',
  getParentRoute: () => AppRoute,
} as any)
const AppImportsIndexRoute = AppImportsIndexRouteImport.update({
  id: '/imports/',
  path: '/imports/',
  getParentRoute: () => AppRoute,
} as any)
const AppImportsImportIdRoute = AppImportsImportIdRouteImport.update({
  id: '/imports/$importId',
  path: '/imports/$importId',
  getParentRoute: () => AppRoute,
} as any)
const AppMappingsIndexRoute = AppMappingsIndexRouteImport.update({
  id: '/mappings/',
  path: '/mappings/',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityIndexRoute = AppQualityIndexRouteImport.update({
  id: '/quality/',
  path: '/quality/',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsIndexRoute = AppSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsSessionIdRoute = AppSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesIndexRoute = AppSourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/imports/$importId': typeof AppImportsImportIdRoute
  '/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/import-assistant/': typeof AppImportAssistantIndexRoute
  '/imports/': typeof AppImportsIndexRoute
  '/mappings/': typeof AppMappingsIndexRoute
  '/quality/': typeof AppQualityIndexRoute
  '/sessions/': typeof AppSessionsIndexRoute
  '/sources/': typeof AppSourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/imports/$importId': typeof AppImportsImportIdRoute
  '/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/import-assistant': typeof AppImportAssistantIndexRoute
  '/imports': typeof AppImportsIndexRoute
  '/mappings': typeof AppMappingsIndexRoute
  '/quality': typeof AppQualityIndexRoute
  '/sessions': typeof AppSessionsIndexRoute
  '/sources': typeof AppSourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/imports/$importId': typeof AppImportsImportIdRoute
  '/_app/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/_app/import-assistant/': typeof AppImportAssistantIndexRoute
  '/_app/imports/': typeof AppImportsIndexRoute
  '/_app/mappings/': typeof AppMappingsIndexRoute
  '/_app/quality/': typeof AppQualityIndexRoute
  '/_app/sessions/': typeof AppSessionsIndexRoute
  '/_app/sources/': typeof AppSourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/imports/$importId'
    | '/sessions/$sessionId'
    | '/import-assistant/'
    | '/imports/'
    | '/mappings/'
    | '/quality/'
    | '/sessions/'
    | '/sources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/imports/$importId'
    | '/sessions/$sessionId'
    | '/import-assistant'
    | '/imports'
    | '/mappings'
    | '/quality'
    | '/sessions'
    | '/sources'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/imports/$importId'
    | '/_app/sessions/$sessionId'
    | '/_app/import-assistant/'
    | '/_app/imports/'
    | '/_app/mappings/'
    | '/_app/quality/'
    | '/_app/sessions/'
    | '/_app/sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import-assistant/': {
      id: '/_app/import-assistant/'
      path: '/import-assistant'
      fullPath: '/import-assistant/'
      preLoaderRoute: typeof AppImportAssistantIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/imports/': {
      id: '/_app/imports/'
      path: '/imports'
      fullPath: '/imports/'
      preLoaderRoute: typeof AppImportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/imports/$importId': {
      id: '/_app/imports/$importId'
      path: '/imports/$importId'
      fullPath: '/imports/$importId'
      preLoaderRoute: typeof AppImportsImportIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mappings/': {
      id: '/_app/mappings/'
      path: '/mappings'
      fullPath: '/mappings/'
      preLoaderRoute: typeof AppMappingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quality/': {
      id: '/_app/quality/'
      path: '/quality'
      fullPath: '/quality/'
      preLoaderRoute: typeof AppQualityIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/': {
      id: '/_app/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AppSessionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/$sessionId': {
      id: '/_app/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AppSessionsSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources/': {
      id: '/_app/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof AppSourcesIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppImportsImportIdRoute: typeof AppImportsImportIdRoute
  AppSessionsSessionIdRoute: typeof AppSessionsSessionIdRoute
  AppImportAssistantIndexRoute: typeof AppImportAssistantIndexRoute
  AppImportsIndexRoute: typeof AppImportsIndexRoute
  AppMappingsIndexRoute: typeof AppMappingsIndexRoute
  AppQualityIndexRoute: typeof AppQualityIndexRoute
  AppSessionsIndexRoute: typeof AppSessionsIndexRoute
  AppSourcesIndexRoute: typeof AppSourcesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppImportsImportIdRoute: AppImportsImportIdRoute,
  AppSessionsSessionIdRoute: AppSessionsSessionIdRoute,
  AppImportAssistantIndexRoute: AppImportAssistantIndexRoute,
  AppImportsIndexRoute: AppImportsIndexRoute,
  AppMappingsIndexRoute: AppMappingsIndexRoute,
  AppQualityIndexRoute: AppQualityIndexRoute,
  AppSessionsIndexRoute: AppSessionsIndexRoute,
  AppSourcesIndexRoute: AppSourcesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
