/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicLoginRouteImport } from './routes/_public.login'
import { Route as PublicRegisterRouteImport } from './routes/_public.register'
import { Route as AppImportAssistantIndexRouteImport } from './routes/_app.import-assistant.index'
import { Route as AppImportsIndexRouteImport } from './routes/_app.imports.index'
import { Route as AppImportsImportIdRouteImport } from './routes/_app.imports.$importId'
import { Route as AppImportsNewRouteImport } from './routes/_app.imports.new'
import { Route as AppMappingsIndexRouteImport } from './routes/_app.mappings.index'
import { Route as AppOverviewIndexRouteImport } from './routes/_app.overview.index'
import { Route as AppQualityIndexRouteImport } from './routes/_app.quality.index'
import { Route as AppSessionsIndexRouteImport } from './routes/_app.sessions.index'
import { Route as AppSessionsSessionIdRouteImport } from './routes/_app.sessions.$sessionId'
import { Route as AppSourcesIndexRouteImport } from './routes/_app.sources.index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const AppImportAssistantIndexRoute = AppImportAssistantIndexRouteImport.update({
  id: '/import-assistant/',
  path: '/import-assistant/',
  getParentRoute: () => AppRoute,
} as any)
const AppImportsIndexRoute = AppImportsIndexRouteImport.update({
  id: '/imports/',
  path: '/imports/',
  getParentRoute: () => AppRoute,
} as any)
const AppImportsImportIdRoute = AppImportsImportIdRouteImport.update({
  id: '/imports/$importId',
  path: '/imports/$importId',
  getParentRoute: () => AppRoute,
} as any)
const AppImportsNewRoute = AppImportsNewRouteImport.update({
  id: '/imports/new',
  path: '/imports/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMappingsIndexRoute = AppMappingsIndexRouteImport.update({
  id: '/mappings/',
  path: '/mappings/',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewIndexRoute = AppOverviewIndexRouteImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityIndexRoute = AppQualityIndexRouteImport.update({
  id: '/quality/',
  path: '/quality/',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsIndexRoute = AppSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsSessionIdRoute = AppSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesIndexRoute = AppSourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/imports/$importId': typeof AppImportsImportIdRoute
  '/imports/new': typeof AppImportsNewRoute
  '/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/import-assistant/': typeof AppImportAssistantIndexRoute
  '/imports/': typeof AppImportsIndexRoute
  '/mappings/': typeof AppMappingsIndexRoute
  '/overview/': typeof AppOverviewIndexRoute
  '/quality/': typeof AppQualityIndexRoute
  '/sessions/': typeof AppSessionsIndexRoute
  '/sources/': typeof AppSourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/imports/$importId': typeof AppImportsImportIdRoute
  '/imports/new': typeof AppImportsNewRoute
  '/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/import-assistant': typeof AppImportAssistantIndexRoute
  '/imports': typeof AppImportsIndexRoute
  '/mappings': typeof AppMappingsIndexRoute
  '/overview': typeof AppOverviewIndexRoute
  '/quality': typeof AppQualityIndexRoute
  '/sessions': typeof AppSessionsIndexRoute
  '/sources': typeof AppSourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/': typeof PublicIndexRoute
  '/_app/imports/$importId': typeof AppImportsImportIdRoute
  '/_app/imports/new': typeof AppImportsNewRoute
  '/_app/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/_app/import-assistant/': typeof AppImportAssistantIndexRoute
  '/_app/imports/': typeof AppImportsIndexRoute
  '/_app/mappings/': typeof AppMappingsIndexRoute
  '/_app/overview/': typeof AppOverviewIndexRoute
  '/_app/quality/': typeof AppQualityIndexRoute
  '/_app/sessions/': typeof AppSessionsIndexRoute
  '/_app/sources/': typeof AppSourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/imports/$importId'
    | '/imports/new'
    | '/sessions/$sessionId'
    | '/import-assistant/'
    | '/imports/'
    | '/mappings/'
    | '/overview/'
    | '/quality/'
    | '/sessions/'
    | '/sources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/imports/$importId'
    | '/imports/new'
    | '/sessions/$sessionId'
    | '/import-assistant'
    | '/imports'
    | '/mappings'
    | '/overview'
    | '/quality'
    | '/sessions'
    | '/sources'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/_public/login'
    | '/_public/register'
    | '/_public/'
    | '/_app/imports/$importId'
    | '/_app/imports/new'
    | '/_app/sessions/$sessionId'
    | '/_app/import-assistant/'
    | '/_app/imports/'
    | '/_app/mappings/'
    | '/_app/overview/'
    | '/_app/quality/'
    | '/_app/sessions/'
    | '/_app/sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/import-assistant/': {
      id: '/_app/import-assistant/'
      path: '/import-assistant'
      fullPath: '/import-assistant/'
      preLoaderRoute: typeof AppImportAssistantIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/imports/': {
      id: '/_app/imports/'
      path: '/imports'
      fullPath: '/imports/'
      preLoaderRoute: typeof AppImportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/imports/$importId': {
      id: '/_app/imports/$importId'
      path: '/imports/$importId'
      fullPath: '/imports/$importId'
      preLoaderRoute: typeof AppImportsImportIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/imports/new': {
      id: '/_app/imports/new'
      path: '/imports/new'
      fullPath: '/imports/new'
      preLoaderRoute: typeof AppImportsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mappings/': {
      id: '/_app/mappings/'
      path: '/mappings'
      fullPath: '/mappings/'
      preLoaderRoute: typeof AppMappingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview/': {
      id: '/_app/overview/'
      path: '/overview'
      fullPath: '/overview/'
      preLoaderRoute: typeof AppOverviewIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quality/': {
      id: '/_app/quality/'
      path: '/quality'
      fullPath: '/quality/'
      preLoaderRoute: typeof AppQualityIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/': {
      id: '/_app/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AppSessionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/$sessionId': {
      id: '/_app/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AppSessionsSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources/': {
      id: '/_app/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof AppSourcesIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppImportsImportIdRoute: typeof AppImportsImportIdRoute
  AppImportsNewRoute: typeof AppImportsNewRoute
  AppSessionsSessionIdRoute: typeof AppSessionsSessionIdRoute
  AppImportAssistantIndexRoute: typeof AppImportAssistantIndexRoute
  AppImportsIndexRoute: typeof AppImportsIndexRoute
  AppMappingsIndexRoute: typeof AppMappingsIndexRoute
  AppOverviewIndexRoute: typeof AppOverviewIndexRoute
  AppQualityIndexRoute: typeof AppQualityIndexRoute
  AppSessionsIndexRoute: typeof AppSessionsIndexRoute
  AppSourcesIndexRoute: typeof AppSourcesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppImportsImportIdRoute: AppImportsImportIdRoute,
  AppImportsNewRoute: AppImportsNewRoute,
  AppSessionsSessionIdRoute: AppSessionsSessionIdRoute,
  AppImportAssistantIndexRoute: AppImportAssistantIndexRoute,
  AppImportsIndexRoute: AppImportsIndexRoute,
  AppMappingsIndexRoute: AppMappingsIndexRoute,
  AppOverviewIndexRoute: AppOverviewIndexRoute,
  AppQualityIndexRoute: AppQualityIndexRoute,
  AppSessionsIndexRoute: AppSessionsIndexRoute,
  AppSourcesIndexRoute: AppSourcesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
